[package]
name = "fujitsu-mpi"
version = "0.1.0"
edition = "2021"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
description = "Fujitsu MPI library for rust."
readme = "README.md"
license = "GPL-3.0-or-later"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "fujitsu-mpi-sys",
  "bed",
]

[dependencies]
anyhow = "1"
fujitsu-mpi-sys = { path="./fujitsu-mpi-sys" }

[[example]]
name = "hello-mpi"

[[example]]
name = "send-recv"

[[example]]
name = "scatter"
